name: "Generate Client Library w/ the OpenAPITools Generator"
description: "Generates a client library from an openapifile using OpenAPITools' generator"
branding:
  icon: target
  color: green

inputs: 
  generator:
    description: The name of the generator (i.e. the language to generate the client library in) to use e.g. "typescript-angular"
    required: true
  config-file:
    description: The path to the config file to be passed along to the OpenAPITools generator
    required: false
    default: UNSET
  openapi-file:
    description: The path to the OpenAPI document to generate a client library for
    required: false
    default: openapi.json
  openapi-url:
    description: If set, the OpenAPI document will be loaded from this URL instead of openapi-file.
    required: false
    default: UNSET
  generator-tag:
    description: The Docker tag of the openapitools/openapi-generator-cli image to use.
    required: false
    default: latest

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        cmd='docker run -u 1001 --rm --workdir /github/workspace -v "$GITHUB_WORKSPACE":"/github/workspace"'
        cmd='$cmd "openapitools/openapi-generator-cli:${{ inputs.generator-tag }}" generate'
        if [[ ${{ inputs.openapi-url }} = "UNSET" ]]; then cmd="$cmd -i /github/workspace/${{ inputs.openapi-file }}"; else cmd="$cmd -i ${{ inputs.openapi-url }}"; fi
        if [[ ${{ inputs.config-file }} != "UNSET" ]]; then  cmd="$cmd -c /github/workspace/${{ inputs.config-file }}"; fi
        cmd="$cmd -g ${{ inputs.generator }} -o /github/workspace/${{ inputs.generator }}-client"
        eval $cmd
    
