name: "Generate Client Library w/ the OpenAPITools Generator"
description: "Generates a client library from an openapifile using OpenAPITools' generator"
branding:
  icon: target
  color: green

inputs: 
  generator:
    description: The name of the generator (i.e. the language to generate the client library in) to use e.g. "typescript-angular"
    required: true
  generator-tag:
    description: The Docker tag of the openapitools/openapi-generator-cli image to use.
    required: false
    default: latest
  openapi-file:
    description: The path to the OpenAPI document to generate a client library for
    required: false
    default: openapi.json
  openapi-url:
    description: If set, the OpenAPI document will be loaded from this URL instead of openapi-file.
    required: false
    default: UNSET
  config-file:
    description: The path to the config file to be passed along to the OpenAPITools generator
    required: false
    default: UNSET
  template-dir:
    description: The path to the folder containing the template files
    required: false
    default: UNSET
  command-args:
    description: Optional, additional arguments to pass through to the generator.
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: python ${{ github.action_path }}/entrypoint.py ${{ inputs.generator }} ${{ inputs.generator-tag }} ${{ inputs.openapi-file }} ${{ inputs.openapi-url }} ${{ inputs.config-file }} ${{ inputs.template-dir }} ${{ inputs.command-args}}