name: "Generate Client Library w/ the OpenAPITools Generator"
description: "Generates a client library from an openapifile using OpenAPITools' generator"
branding:
  icon: target
  color: green

inputs: 
  generator:
    description: The name of the generator (i.e. the language to generate the client library in) to use e.g. "typescript-angular"
    required: true
  config-file:
    description: The path to the config file to be passed along to the OpenAPITools generator
    required: false
    default: UNSET
  openapi-file:
    description: The path to the OpenAPI document to generate a client library for
    required: false
    default: openapi.json
  openapi-url:
    description: If set, the OpenAPI document will be loaded from this URL instead of openapi-file.
    required: false
    default: UNSET
  generator-tag:
    description: The Docker tag of the openapitools/openapi-generator-cli image to use.
    required: false
    default: latest

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        document=${{ inputs.openapi-url }} && [[ ${{ inputs.openapi-url }} = "UNSET" ]] && document="/github/workspace/${{ inputs.openapi-file }}"
        config="-c /github/workspace/${{ inputs.config-file }}" && [[ ${{ inputs.config-file }} = "UNSET" ]] && ""
        docker run -u 1001 --rm --workdir /github/workspace -v "$GITHUB_WORKSPACE":"/github/workspace" \
          "openapitools/openapi-generator-cli:${{ inputs.generator-tag }}" generate \
          -i "$document" \
          -g "${{ inputs.generator }}" \
          "$config" \
          -o "/github/workspace/${{ inputs.generator }}-client"
    
