name: Run Checks

on:
  push

jobs:
  smoke-test-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: rust
          config-file: test_data/config.yml
          openapi-url: https://raw.githubusercontent.com/openapi-generators/openapi-python-client/main/end_to_end_tests/openapi.json
  smoke-test-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: rust
          config-file: test_data/config.yml
          openapi-file: test_data/openapi.json
  test-openapi-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: rust
          config-file: test_data/config.yml
          openapi-file: test_data/openapi.json
          generator-tag: v5.0.0